# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public/%env(RESULT_MEDIA_DIRECTORY)%'
                    - '%kernel.project_dir%/public/%env(USER_MEDIA_DIRECTORY)%'

    filter_sets:
        cache: ~
        user_photo_icon_widen:
            filters:
                relative_resize:
                    widen: 32
        user_photo_thumbnail_widen:
            filters:
                relative_resize:
                    widen: 128
        user_photo_widen:
            filters:
                relative_resize:
                    widen: 896
        result_image_icon_widen:
            filters:
                relative_resize:
                    widen: 32
        result_image_thumbnail_widen:
            filters:
                relative_resize:
                    widen: 384
        result_image_widen:
            filters:
                relative_resize:
                    widen: 896