vich_uploader:
    db_driver: orm
    mappings:
        result_media:
            uri_prefix: '/%env(RESULT_MEDIA_DIRECTORY)%'
            upload_destination: '%kernel.project_dir%/public/%env(RESULT_MEDIA_DIRECTORY)%'
            delete_on_remove: true
            delete_on_update: true
            namer: vich_uploader.namer_uniqid