#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout

index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    defaults: {_locale: en}
    methods: [GET]
    requirements:
        _locale: en|ru

results_index:
    path: /{_locale}/results
    controller: App\Controller\ResultController::index
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

results_create:
    path: /{_locale}/results/create
    controller: App\Controller\ResultController::create
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

results_by_user:
    path: /{_locale}/results/{user}
    controller: App\Controller\ResultController::indexByUser
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

steps:
    path: /{_locale}/trading/martingail/steps
    controller: App\Controller\StatisticController::steps
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

profitability:
    path: /{_locale}/trading/profitability
    controller: App\Controller\StatisticController::tradingProfitability
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"