#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout

index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    defaults: {_locale: en}
    methods: [GET]
    requirements:
        _locale: en|ru

results_index:
    path: /{_locale}/result
    controller: App\Controller\ResultController::index
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

result_create:
    path: /{_locale}/result/create
    controller: App\Controller\ResultController::create
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

results_by_user:
    path: /{_locale}/result/{user}
    controller: App\Controller\ResultController::indexByUser
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

steps:
    path: /{_locale}/trading/martingail/steps
    controller: App\Controller\StatisticController::steps
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

trading_profitability:
    path: /{_locale}/trading/profitability
    controller: App\Controller\StatisticController::tradingProfitability
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

user_index:
    path: /{_locale}/user
    controller: App\Controller\UserController::index
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

user_trading_profitability:
    path: /{_locale}/trading/profitability/user/{user}
    controller: App\Controller\StatisticController::userTradingProfitability
    defaults: {_locale: en}
    methods: [GET, POST]
    requirements:
        _locale: en|ru

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"